name: Build and push Docker image

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - '.cursor/**'
      - '.vscode/**'
  workflow_dispatch:

jobs:
  scan:
    uses: vaultspeed-labs/github-workflows/.github/workflows/grype.yaml@main
    with:
      image-tag: ${{ github.event.repository.name }}:scan
    secrets: inherit

  docker:
    needs: scan
    uses: vaultspeed-labs/github-workflows/.github/workflows/docker.yaml@main
    secrets: inherit
